# -*- coding: utf-8 -*-
"""DemandForecasting.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AF2BWS7zkLkO3iGMQzlTA1uN2fkiYwL4

DEMAND FORECASTING FOR RETAIL

Date - The date of the transaction or record.

Store ID - Unique identifier for each store.

Product ID - Unique identifier for each product.

Category - Product category (e.g., Groceries, Toys, Electronics).

Region - The geographical region where the store is located.

Inventory Level - The number of units available in stock.

Units Sold - The number of units sold on that date.

Units Ordered - The number of units ordered for restocking.

Demand Forecast - Predicted demand for the product.

Price - Selling price of the product.

Discount - Discount applied to the product (percentage).

Weather Condition - Weather on that date (e.g., Rainy, Sunny, Cloudy).

Holiday/Promotion - Binary (0 or 1) indicating if there was a holiday or promotion.

Competitor Pricing - Competitor's price for the same/similar product

Seasonality - Season classification (e.g., Summer, Autumn).
"""

yimport pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv("/content/Main Project.csv")

print(df.info())
print(df.head())

#checking for null values
print(df.isnull().sum())

df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)
df = df.sort_values(by='Date')  # Ensure data is sorted by time

df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month
df['day_of_week'] = df['Date'].dt.dayofweek
df['is_weekend'] = df['day_of_week'].apply(lambda x: 1 if x >= 5 else 0)

df = df.drop(columns=['Date'])

import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(x=df['Demand Forecast'])
plt.show()

df['Demand Forecast'] = df['Demand Forecast'].clip(lower=df['Demand Forecast'].quantile(0.05), upper=df['Demand Forecast'].quantile(0.95))

import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(x=df['Demand Forecast'])
plt.show()

#Lag Features (for time-series forecasting)#
#df['Demand Forecast_lag_1'] = df['Demand Forecast'].shift(1)  # Previous day's sales
#df['Demand Forecast_lag_7'] = df['Demand Forecast'].shift(7)  # Sales from 7 days ago

#Rolling Mean Features (for trend smoothing)
#df['Demand Forecast_rolling_7'] = df['Demand Forecast'].rolling(window=7).mean()

from sklearn.preprocessing import LabelEncoder
df = pd.get_dummies(df, columns=['Category','Region','Weather Condition','Seasonality'], drop_first=True)

# Distribution of target variable (MEDV)
plt.figure(figsize=(8, 5))
sns.histplot(df['Demand Forecast'], bins=30, kde=True, color='blue')
plt.title("Demand forecasting of Retail")
plt.xlabel("Demand Forecast")
plt.ylabel("Frequency")
plt.show()

train_size = int(len(df) * 0.8)  # 80% train, 20% test
train, test = df[:train_size], df[train_size:]

from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder object
label_encoder = LabelEncoder()

# Fit and transform the 'Store ID' column
df['Store ID'] = label_encoder.fit_transform(df['Store ID'])

# Fit and transform the 'Product ID' column
df['Product ID'] = label_encoder.fit_transform(df['Product ID'])

# Correlation heatmap
plt.figure(figsize=(12, 8))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm", fmt=".2f", linewidths=0.5)
plt.title("Feature Correlation Heatmap")
plt.show()

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.impute import SimpleImputer

target_column = 'Demand Forecast'  # Replace with actual target column
df = df.dropna()
X = df.drop(columns=[target_column])
y = df[target_column]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=False)

# Create a LabelEncoder object
label_encoder_store = LabelEncoder()
label_encoder_product = LabelEncoder()

# Fit and transform the 'Store ID' column on training data
X_train['Store ID'] = label_encoder_store.fit_transform(X_train['Store ID'])
X_test['Store ID'] = label_encoder_store.transform(X_test['Store ID'])

# Fit and transform the 'Product ID' column on training data
X_train['Product ID'] = label_encoder_product.fit_transform(X_train['Product ID'])
X_test['Product ID'] = label_encoder_product.transform(X_test['Product ID'])



# Train Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Model Evaluation
r2 = r2_score(y_test, y_pred)
#rmse = mean_squared_error(y_test, y_pred, squared=False)
rmse = mean_squared_error(y_test, y_pred) ** 0.5

print(f"R² Score: {r2:.4f}")
print(f"RMSE: {rmse:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns

# Scatter plot of actual vs predicted values
plt.figure(figsize=(8, 6))
sns.scatterplot(x=y_test, y=y_pred, alpha=0.7)
plt.xlabel("Actual Demand")
plt.ylabel("Predicted Demand")
plt.title("Actual vs. Predicted Demand")
plt.axline([0, 0], [1, 1], color="red", linestyle="--")
plt.show()

df

# Define feature values manually
input_data = {
    "Store ID": (input("Enter Store ID: ")),
    "Product ID": (input("Enter Product ID: ")),
    "Inventory Level": float(input("Enter Inventory Level: ")),
    "Units Sold": float(input("Enter Units Sold: ")),
    "Units Ordered": float(input("Enter Units Ordered: ")),
    "Price": float(input("Enter Price: ")),
    "Discount": float(input("Enter Discount: ")),
    "Holiday/Promotion": int(input("Is it a Holiday/Promotion? (1 for Yes, 0 for No): ")),
    "Competitor Pricing": float(input("Enter Competitor Pricing: ")),
    "year": int(input("Enter Year: ")),
    "month": int(input("Enter Month: ")),
    "day_of_week": int(input("Enter Day of the Week (0=Monday, 6=Sunday): ")),
    "is_weekend": int(input("Is it a Weekend? (1 for Yes, 0 for No): ")),

    # One-Hot Encoded Categorical Features
    "Category_Electronics": int(input("Is Category Electronics? (1 for Yes, 0 for No): ")),
    "Category_Furniture": int(input("Is Category Furniture? (1 for Yes, 0 for No): ")),
    "Category_Groceries": int(input("Is Category Groceries? (1 for Yes, 0 for No): ")),
    "Category_Toys": int(input("Is Category Toys? (1 for Yes, 0 for No): ")),
    "Region_North": int(input("Is Region North? (1 for Yes, 0 for No): ")),
    "Region_South": int(input("Is Region South? (1 for Yes, 0 for No): ")),
    "Region_West": int(input("Is Region West? (1 for Yes, 0 for No): ")),
    "Weather Condition_Rainy": int(input("Is Weather Rainy? (1 for Yes, 0 for No): ")),
    "Weather Condition_Snowy": int(input("Is Weather Snowy? (1 for Yes, 0 for No): ")),
    "Weather Condition_Sunny": int(input("Is Weather Sunny? (1 for Yes, 0 for No): ")),
    "Seasonality_Spring": int(input("Is Season Spring? (1 for Yes, 0 for No): ")),
    "Seasonality_Summer": int(input("Is Season Summer? (1 for Yes, 0 for No): ")),
    "Seasonality_Winter": int(input("Is Season Winter? (1 for Yes, 0 for No): ")),

}
# Convert to DataFrame
import pandas as pd
input_df = pd.DataFrame([input_data])


input_df['Store ID'] = label_encoder_store.transform(input_df['Store ID'])
input_df['Product ID'] = label_encoder_product.transform(input_df['Product ID'])


# Predict house price
predicted_price = model.predict(input_df)[0]

print(f" Predicted House Price (MEDV): {predicted_price:.2f}")

import joblib
from sklearn.preprocessing import StandardScaler # Import StandardScaler
scaler = StandardScaler()
#save the model
joblib.dump(model,"Demandforecast_model.pkl")
joblib.dump(scaler, "scaler.pkl")

pip install streamlit -q

import streamlit as st
import pandas as pd
import joblib

# Load the trained model and scaler
model = joblib.load("Demandforecast_model.pkl")
scaler = joblib.load("scaler.pkl")

st.title("Retail Demand Forecasting App")
st.write("Fill in the values below to predict demand:")

# Collect user input
store_id = st.number_input("Store ID", min_value=1)
product_id = st.number_input("Product ID", min_value=1)
inventory_level = st.number_input("Inventory Level")
units_sold = st.number_input("Units Sold")
units_ordered = st.number_input("Units Ordered")
price = st.number_input("Price")
discount = st.number_input("Discount (%)")
holiday_promotion = st.selectbox("Holiday/Promotion", [0, 1])
competitor_pricing = st.number_input("Competitor Pricing")
year = st.number_input("Year", min_value=2020, max_value=2030)
month = st.number_input("Month", min_value=1, max_value=12)
day_of_week = st.number_input("Day of Week", min_value=0, max_value=6)
is_weekend = st.selectbox("Is Weekend", [0, 1])

# One-hot encoded category options
category_electronics = st.selectbox("Category Electronics?", [0, 1])
category_furniture = st.selectbox("Category Furniture?", [0, 1])
category_groceries = st.selectbox("Category Groceries?", [0, 1])
category_toys = st.selectbox("Category Toys?", [0, 1])
region_north = st.selectbox("Region North?", [0, 1])
region_south = st.selectbox("Region South?", [0, 1])
region_west = st.selectbox("Region West?", [0, 1])
weather_rainy = st.selectbox("Weather Rainy?", [0, 1])
weather_snowy = st.selectbox("Weather Snowy?", [0, 1])
weather_sunny = st.selectbox("Weather Sunny?", [0, 1])
season_spring = st.selectbox("Season Spring?", [0, 1])
season_summer = st.selectbox("Season Summer?", [0, 1])
season_winter = st.selectbox("Season Winter?", [0, 1])

if st.button("Predict Demand"):
    input_features = pd.DataFrame([
        [store_id, product_id, inventory_level, units_sold, units_ordered, price, discount,
         holiday_promotion, competitor_pricing, year, month, day_of_week, is_weekend,
         category_electronics, category_furniture, category_groceries, category_toys,
         region_north, region_south, region_west, weather_rainy, weather_snowy, weather_sunny,
         season_spring, season_summer, season_winter]
    ], columns=['Store ID', 'Product ID', 'Inventory Level', 'Units Sold', 'Units Ordered', 'Price', 'Discount',
                'Holiday/Promotion', 'Competitor Pricing', 'year', 'month', 'day_of_week', 'is_weekend',
                'Category_Electronics', 'Category_Furniture', 'Category_Groceries', 'Category_Toys',
                'Region_North', 'Region_South', 'Region_West', 'Weather Condition_Rainy', 'Weather Condition_Snowy',
                'Weather Condition_Sunny', 'Seasonality_Spring', 'Seasonality_Summer', 'Seasonality_Winter'])

    prediction = model.predict(input_features)[0]
    st.success(f"Predicted Demand Forecast: {prediction:.2f}")

!wget -q -O - ipv4.icanhazip.com

! streamlit run app.py & npx localtunnel --port 8501